const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const ts=require('typescript');const {PGlite}=require('@electric-sql/pglite');
test('factory requests: isolated jobs, permissions, partial completion, attachments and PDF copies',async t=>{
 const database=new PGlite();const loaded=new Map();let currentUser=null;
 const tagged=(strings,...values)=>{let query=strings[0];values.forEach((value,index)=>{query+=`$${index+1}`+strings[index+1];});return {then:(resolve,reject)=>database.query(query,values).then(result=>result.rows).then(resolve,reject)};};
 tagged.transaction=async queries=>{await database.query('BEGIN');try{const results=[];for(const query of queries)results.push(await query);await database.query('COMMIT');return results;}catch(error){await database.query('ROLLBACK');throw error;}};
 const mocks={'@neondatabase/serverless':{neon:()=>tagged},'next/headers':{cookies:async()=>({get:()=>({value:'test-session'})})},'next/server':{NextResponse:{json:(value,init={})=>new Response(JSON.stringify(value),{...init,headers:{'Content-Type':'application/json',...init.headers}})}}};
 function load(file){if(file.endsWith(".json"))return JSON.parse(fs.readFileSync(file,"utf8"));if(loaded.has(file))return loaded.get(file);const module={exports:{}};const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;const requireModule=name=>name==='@/lib/auth'&&loaded.has('lib/auth.ts')?{...loaded.get('lib/auth.ts'),getSessionUser:async()=>currentUser}:mocks[name]??(name.startsWith('@/')?load(name.slice(2)+(name.endsWith('.json')?'':'.ts')):require(name));new Function('module','exports','require','process','crypto',code)(module,module.exports,requireModule,{env:{DATABASE_URL:'postgres://test'}},require('node:crypto').webcrypto);loaded.set(file,module.exports);return module.exports;}
 const auth=load('lib/auth.ts'),production=load('lib/production-server.ts'),model=load('lib/factory-requests.ts'),server=load('lib/factory-request-server.ts'),route=load('app/api/factory-requests/route.ts');
 await auth.ensureAuthSchema();await database.query("INSERT INTO portal_users(id,name,username,password_hash,role) VALUES ('admin','Admin','admin','test','Admin'),('cs','Julia','cs','test','Customer Service'),('other','Other','other','test','Customer Service'),('mesh','Furkan','mesh','test','Mesh')");
 const admin={id:'admin',name:'Admin',role:'Admin',permissions:[],active:true};const cs={id:'cs',name:'Julia',role:'Customer Service',permissions:['Edit Orders'],active:true};const other={...cs,id:'other'};const mesh={id:'mesh',name:'Furkan',role:'Mesh',permissions:['View Daily Production','Complete Mesh'],active:true};
 await production.ensureProductionSchema();await require('./production-fixtures.cjs').seedProductionFixtures(database,load('lib/order-pool.ts').poolOrders.map(o=>({...o,items:o.items.map(i=>({...i,widthMm:1285,heightMm:2108,reference:'Bedroom'}))})));const snapshot=await production.productionSnapshot();const order=snapshot.orders.find(o=>o.items.length>=2);const input=category=>({orderId:order.id,category,priority:'Acil',description:'Üretim listesi önemli notu',attachments:[],jobs:order.items.slice(0,2).map(i=>({...model.newJob(i,category),widthMm:"900",heightMm:"2100"}))});let remake,parts,info;
 const change=(r,action,payload={},actor=admin)=>server.changeFactoryRequests([{id:r.id,version:r.version,action,payload}],actor).then(v=>v[0]);
 await t.test('multiple items create independent pending requests without production side effects',async()=>{remake=await server.createFactoryRequest(input(model.requestCategories[0]),cs);const another=await server.createFactoryRequest(input(model.requestCategories[0]),cs);assert.notEqual(remake.number,another.number);assert.equal(remake.status,'Onay Bekliyor');assert.equal(remake.jobs.length,2);assert.equal((await server.factoryRequests(mesh)).length,0);assert.deepEqual((await production.productionSnapshot()).items,snapshot.items);assert.equal(remake.creatorName,'Julia');});
 await t.test('CS only edits own unapproved requests; production writes and order sources remain protected',async()=>{await assert.rejects(change(remake,'approve',{},cs),/FORBIDDEN/);await assert.rejects(server.changeFactoryRequests([{id:remake.id,version:remake.version,action:'edit',payload:input(model.requestCategories[0])}],other),/FORBIDDEN/);const edited={...remake,description:'Yeni not',jobs:remake.jobs};remake=await change(remake,'edit',edited,cs);assert.equal(remake.description,'Yeni not');remake=await change(remake,'approve');assert.equal(remake.status,'Üretime Hazır');assert.equal((await server.factoryRequests(mesh)).length,0);await assert.rejects(change(remake,'edit',edited,cs),/FORBIDDEN/);});
 await t.test('manual release, duplicate release prevention, one item completes while another stays open',async()=>{remake=await change(remake,'release',{jobIds:remake.jobs.map(j=>j.id)});await assert.rejects(change(remake,'release',{jobIds:[remake.jobs[0].id]}),/CONFLICT/);const job=remake.jobs[0];await assert.rejects(change(remake,'complete',{jobId:job.id,station:'Frame'},mesh),/CONFLICT/);remake=await change(remake,'complete',{jobId:job.id,station:'Mesh'},mesh);assert.equal(remake.jobs[0].step,1);assert.equal(remake.jobs[1].step,0);const queue=await server.factoryRequests({...mesh,permissions:[...mesh.permissions,'View Factory Requests']});assert.equal(queue.find(r=>r.id===remake.id).jobs.length,1);await assert.rejects(change({...remake,version:remake.version-1},'complete',{jobId:job.id,station:'Mesh'},mesh),/CONFLICT/);for(const station of remake.jobs[0].stations.slice(1))remake=await change(remake,'complete',{jobId:job.id,station});assert.equal(model.jobStatus(remake.jobs[0]),'Gönderildi');assert.equal(remake.jobs[1].step,0);assert.equal((await production.productionSnapshot()).items.length,0);});
 await t.test('one item supports two parts with different station routes and independent quantities',async()=>{const value=input(model.requestCategories[1]);value.jobs=[model.newJob(order.items[0],model.requestCategories[1]),model.newJob(order.items[0],model.requestCategories[1])];value.jobs[0].operation='Tül';value.jobs[0].meshType='Pollen';value.jobs[0].note='Sadece tül gönderilecek';value.jobs[1].operation='Profil';value.jobs[1].profileLengthMm='1250';value.jobs[1].profileType='Eşik';value.jobs[1].color='Antrasit 7016';value.jobs[1].stations=model.defaultStations(value.category,value.jobs[1].operation);parts=await server.createFactoryRequest(value,cs);parts=await change(parts,'approve');parts=await change(parts,'release',{jobIds:parts.jobs.map(j=>j.id)});assert.equal(parts.jobs[0].itemId,parts.jobs[1].itemId);assert.notEqual(parts.jobs[0].id,parts.jobs[1].id);assert.equal(model.taskStation(parts.jobs[0]),'Mesh');assert.equal(model.taskStation(parts.jobs[1]),'Frame');});
 await t.test('only two categories accepted; legacy information records remain readable and cannot convert or release',async()=>{assert.equal(model.requestCategories.length,2);const value=input(model.legacyInfoCategory);await assert.rejects(server.createFactoryRequest(value,cs),/VALIDATION/);const legacy={...remake,id:'old-info',number:'FT-LEGACY',category:model.legacyInfoCategory,status:'Bilgi Bekleniyor',jobs:remake.jobs.map(j=>({...j,releasedAt:null,step:0,stations:[]}))};await database.query('INSERT INTO portal_factory_requests(id,number,data,version) VALUES ($1,$2,$3,$4)',[legacy.id,legacy.number,JSON.stringify(legacy),legacy.version]);await assert.rejects(change(legacy,'convert'),/VALIDATION/);await assert.rejects(change(legacy,'release',{jobIds:legacy.jobs.map(j=>j.id)}),/CONFLICT/);assert.ok((await server.factoryRequests(admin)).some(r=>r.id===legacy.id));});
 await t.test('dynamic part types validate required fields, fixed colors, profile millimeters and source dimensions',async()=>{
 const make=operation=>{const v=input(model.requestCategories[1]);v.jobs=[{...model.newJob(order.items[0],v.category),operation,quantity:2}];return v;};
 for(const operation of model.partTypes){const v=make(operation);Object.assign(v.jobs[0],{meshType:'Pollen',curtainType:'Blackout',curtainColor:'Beyaz',profileType:'Kanat',profileLengthMm:'2100',plasticType:'Tekerlek (Standart)',color:'Beyaz 9016',lengthCm:'123',widthMm:'1',heightMm:'2'});const r=await server.createFactoryRequest(v,cs);const j=r.jobs[0];if(model.isFabricPart(operation)){assert.equal(j.widthMm,'1285');assert.equal(j.heightMm,'2108');}if(operation==='Profil'){assert.equal(j.profileLengthMm,'2100');assert.equal(j.widthMm,'');assert.equal(j.lengthCm,'');}if(operation==='Plastikler'){assert.equal(j.profileLengthMm,'');assert.equal(j.heightMm,'');}if(operation==='Tül + Perde'){assert.equal(j.meshType,'Pollen');assert.equal(j.curtainType,'Blackout');assert.equal(j.curtainColor,'Beyaz');}}
 const many=make('Plastikler');many.jobs=Array.from({length:101},()=>({...model.newJob(order.items[0],many.category),operation:'Plastikler',plasticType:'Tekerlek (Standart)',color:'Siyah 9005'}));assert.equal(model.validateRequestInput(many,[order]).jobs.length,101);
 const v=make('Profil');Object.assign(v.jobs[0],{profileType:'Kanat',profileLengthMm:'2100',color:'RAL 7006'});await assert.rejects(server.createFactoryRequest(v,cs),/VALIDATION/);v.jobs[0].color='Krem 9001';v.jobs[0].profileType='Diğer';await assert.rejects(server.createFactoryRequest(v,cs),/VALIDATION/);
 const plastic=make('Plastikler');Object.assign(plastic.jobs[0],{plasticType:'Tekerlek (Standart)',color:'Krem 9001'});await assert.rejects(server.createFactoryRequest(plastic,cs),/VALIDATION/);
 const cloth=make('Tül + Perde');cloth.jobs[0].meshType='Pollen';await assert.rejects(server.createFactoryRequest(cloth,cs),/VALIDATION/);
 const historical={...model.newJob(order.items[0],model.requestCategories[1]),operation:'Eşik profili',lengthCm:'125',color:'RAL 7016'};const adapted=model.editableJob(historical);assert.equal(adapted.profileLengthMm,'1250');assert.equal(adapted.operation,'Profil');assert.equal(historical.operation,'Eşik profili');
 assert.equal(model.itemSummary(order.items[0],0),'Kalem 1 / 128,5 × 210,8 / '+order.items[0].color+' / '+order.items[0].name+' / Bedroom');
 const missing={...order,items:order.items.map(i=>({...i,widthMm:undefined,heightMm:undefined}))};const raw=input(model.requestCategories[0]);raw.jobs[0].widthMm='999';const canonical=model.validateRequestInput(raw,[missing]);assert.equal(canonical.jobs[0].widthMm,'');assert.throws(()=>server.evolveRequest({...remake,jobs:canonical.jobs,status:'Üretime Hazır'},'release',{jobIds:canonical.jobs.map(j=>j.id)},admin),/VALIDATION/);
 });
 await t.test('CS source order edit does not create a factory request or change source production stages',async()=>{const before=await server.factoryRequests(admin);await production.editProductionOrder({...order,customer:'CS Updated',items:order.items.map(i=>({...i,widthMm:950,heightMm:2200}))},cs);const after=await server.factoryRequests(admin);assert.deepEqual(after,before);assert.equal((await production.productionSnapshot()).orders.find(o=>o.id===order.id).items[0].widthMm,950);});
 await t.test('API rejects unauthorized and cross-origin writes',async()=>{currentUser=mesh;const post=body=>route.POST(new Request('https://rescro.test/api/factory-requests',{method:'POST',headers:{'content-type':'application/json',origin:'https://rescro.test'},body:JSON.stringify(body)}));assert.equal((await post({action:'create',input:input(model.requestCategories[0])})).status,403);assert.equal((await route.GET(new Request('https://rescro.test/api/factory-requests?orders=1'))).status,403);currentUser=cs;assert.equal((await route.POST(new Request('https://rescro.test/api/factory-requests',{method:'POST',headers:{'content-type':'application/json',origin:'https://foreign.test'},body:'{}'}))).status,403);});
 await t.test('single and double A4 PDFs preserve notes, Turkish text and records; long notes paginate',async()=>{const {factoryRequestPdf}=load('lib/factory-request-pdf.ts');const {PDFDocument}=require('pdf-lib');const before=await server.factoryRequests(admin);const sample={...parts,jobs:parts.jobs.map(j=>({...j,note:j.operation==='Tül'?'Sadece tül gönderilecek. Perde beyaz olacak.':'Profil boyu ölçüye göre kesilecek.'}))};for(const copies of [1,2]){const data=await factoryRequestPdf([sample],copies);fs.mkdirSync('tmp/pdfs',{recursive:true});fs.writeFileSync(`tmp/pdfs/factory-${copies}.pdf`,data);const doc=await PDFDocument.load(data);assert.ok(doc.getPageCount()>=1);assert.equal(Math.round(doc.getPages()[0].getWidth()),595);assert.equal(Math.round(doc.getPages()[0].getHeight()),842);}const long={...sample,jobs:[{...sample.jobs[0],note:'Uzun notlar kesilmeden korunur.\n'.repeat(120)}]};const longData=await factoryRequestPdf([long],2);fs.writeFileSync('tmp/pdfs/factory-long.pdf',longData);const doc=await PDFDocument.load(longData);assert.ok(doc.getPageCount()>2);const compact=await factoryRequestPdf([{...sample,jobs:[{...sample.jobs[0],note:'Sadece tül gönderilecek'}],description:''}],2);fs.writeFileSync('tmp/pdfs/factory-compact.pdf',compact);assert.equal((await PDFDocument.load(compact)).getPageCount(),1);assert.deepEqual(await server.factoryRequests(admin),before);});
 await t.test('attachments persist and Admin edits retain active jobs and station history',async()=>{
 const value=input(model.requestCategories[0]);value.attachments=[{id:'file-1',name:'test.txt',mime:'text/plain',data:Buffer.from('Fabrika notu').toString('base64')}];const attached=await server.createFactoryRequest(value,cs);assert.equal(attached.attachments[0].name,'test.txt');
 const before=structuredClone(remake.jobs);remake=await change(remake,'edit',{...remake,description:'Admin üretim notunu güncelledi'},admin);assert.equal(remake.jobs[0].step,before[0].step);assert.deepEqual(remake.jobs[0].completions,before[0].completions);assert.equal(remake.status,'Üretime Verildi');
 });
 await database.close();
});
