const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript');
function load(file){if(file.endsWith('.json'))return JSON.parse(fs.readFileSync(file,'utf8'));const m={exports:{}};const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;new Function('module','exports','require',code)(m,m.exports,name=>name.startsWith('@/')?load(name.slice(2)+(name.endsWith('.json')?'':'.ts')):require(name));return m.exports;}
const i18n=load('lib/i18n.ts');
test('all four language catalogues have matching keys and English fallback',()=>{const en=load('locales/en.json');for(const lang of i18n.languages){const dict=load(`locales/${lang}.json`);assert.deepEqual(Object.keys(dict).sort(),Object.keys(en).sort());for(const [key,value]of Object.entries(dict)){assert.equal(typeof value,'string');assert.equal(i18n.translate(lang,key).includes('undefined'),false);}}
 assert.equal(i18n.translate('en','Fabrika Talepleri'),'Factory Requests');assert.equal(i18n.translate('nl','Mesh'),'Gaas');assert.equal(i18n.translate('de','Packaging'),'Verpackung');assert.equal(i18n.translate('tr','Cord & Eyelet'),'İp ve Kuşgözü');});
test('user preference keys are independent and versioned',()=>{assert.notEqual(i18n.languagePreferenceKey('furkan'),i18n.languagePreferenceKey('edvard'));assert.notEqual(i18n.languagePreferenceKey(null),i18n.languagePreferenceKey('admin'));assert(i18n.languagePreferenceKey('admin').includes(':v1:'));});
test('interpolation and countdown translation preserve numbers and unknown values',()=>{assert.equal(i18n.translate('en','Sipariş 2 gün gecikti'),'Order is 2 days overdue');assert.equal(i18n.translate('de','{0} gün kaldı',{0:5}),'Noch 5 Tage');assert.equal(i18n.translate('nl','Show {0} orders',{0:'QA101-1'}),'Toon QA101-1-bestellingen');assert.equal(i18n.translate('en','VALIDATION: Tül türü girin.'),'Enter a mesh type.');for(const lang of i18n.languages)for(const value of ['QA101-1','1285 × 2108 mm','RAL 7016','Kleur hoekdoppen: Antraciet','My free customer note'])assert.equal(i18n.translate(lang,value),value);});
test('locale-specific dates do not change source dates or instruction values',()=>{const date='08/10/2026';assert.equal(i18n.formatDisplayDate(date,'en'),'08/10/2026');assert.equal(i18n.formatDisplayDate(date,'de'),'08.10.2026');assert.equal(i18n.formatDisplayDate('not a date','tr'),'not a date');const model=load('lib/order-instructions.ts');const item={id:'real-item',name:'QA Screen',quantity:2,color:'RAL 7016',manufactured:true,widthMm:1285,heightMm:2108,properties:'Kleur hoekdoppen: Antraciet'};const before=structuredClone(item);for(const lang of i18n.languages){const instruction=model.instructionFor(item,0);assert.equal(instruction.width,1285);assert.equal(instruction.height,2108);assert.equal(instruction.exampleMeasurements,false);i18n.translate(lang,'Frame');assert.deepEqual(item,before);}});
test('every literal translation call has a catalogue entry; options retain explicit source values',()=>{function walk(p){return fs.readdirSync(p,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(`${p}/${e.name}`):[`${p}/${e.name}`]);}const dictionary=load('locales/en.json');for(const file of [...walk('app'),...walk('components')].filter(p=>p.endsWith('.tsx')&&!p.includes('/ui/'))){const sf=ts.createSourceFile(file,fs.readFileSync(file,'utf8'),ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);function visit(n){if(ts.isCallExpression(n)&&n.expression.getText(sf)==='t'&&ts.isStringLiteral(n.arguments[0]))assert(Object.hasOwn(dictionary,n.arguments[0].text.trim()),file+': '+n.arguments[0].text);if(ts.isJsxElement(n)&&n.openingElement.tagName.getText(sf)==='option')assert(n.openingElement.attributes.properties.some(a=>ts.isJsxAttribute(a)&&a.name.getText(sf)==='value'),file+': option has no source value');ts.forEachChild(n,visit);}visit(sf);}});
test('A4 generation supports four languages without changing job notes or source dimensions',async()=>{const {factoryRequestPdf}=load('lib/factory-request-pdf.ts'),{PDFDocument}=require('pdf-lib');const {newJob,requestCategories}=load('lib/factory-requests.ts');const item={id:'qa-item',name:'QA Screen',quantity:2,color:'RAL 7016',manufactured:true,widthMm:1285,heightMm:2108};const job={...newJob(item,requestCategories[0]),note:'Kleur hoekdoppen: Antraciet - Free note stays raw'};const request={id:'qa-request',number:'QA-REQ-1',orderId:'QA101-1',category:requestCategories[0],priority:'Acil',description:'Original customer note',status:'Üretime Hazır',jobs:[job]};const before=structuredClone(request);for(const lang of i18n.languages){const bytes=await factoryRequestPdf([request],2,undefined,lang);const pdf=await PDFDocument.load(bytes);assert.equal(pdf.getTitle(),i18n.translate(lang,'RESCRO Factory Production List'));assert(pdf.getPageCount()>0);assert.deepEqual(request,before);}});
