const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript');
const React=require('react'),{renderToStaticMarkup}=require('react-dom/server');const mocks={'next/navigation':{},'@/components/ui/badge':{Badge:({children})=>React.createElement('span',null,children)},'@/lib/release':{},'@/components/production-provider':{},'@/components/auth-provider':{},'@/components/legacy-shell':{}};
const loaded=new Map();function load(file){if(loaded.has(file))return loaded.get(file);const module={exports:{}};const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText;new Function('module','exports','require',code)(module,module.exports,name=>mocks[name]??(name.startsWith('@/')?load(name.slice(2)+(fs.existsSync(name.slice(2)+'.ts')?'.ts':'.tsx')):require(name)));loaded.set(file,module.exports);return module.exports;}
const model=load('lib/order-instructions.ts'),{poolOrders}=load('lib/order-pool.ts');
test('recorded order dimensions override prototype examples without mutating source',()=>{const item={...poolOrders[0].items[0],widthMm:1285,heightMm:2108};const before=structuredClone(item);const values=model.instructionFor(item,2);assert.equal(values.width,1285);assert.equal(values.height,2108);assert.equal(values.meshLength,'206.6');assert.equal(values.exampleMeasurements,false);assert.deepEqual(item,before);});
test('historical prototype display returns while source data stays unchanged',()=>{const item=poolOrders[0].items[0];const before=structuredClone(item);for(const index of [0,1,2]){const value=model.instructionFor(item,index);assert.equal(value.width,900+index*100);assert.equal(value.height,2100+index*50);assert.equal(value.exampleMeasurements,true);}assert.deepEqual(item,before);assert.equal(item.widthMm,undefined);});
test('unknown real items never receive fabricated dimensions; known partial values remain visible',()=>{const item={...poolOrders[0].items[0],id:'shopify-real-item',widthMm:1350};const value=model.instructionFor(item,0);assert.equal(value.width,1350);assert.equal(value.height,null);assert.equal(value.meshLength,null);assert.equal(value.cordLength,null);assert.equal(value.exampleMeasurements,false);assert.equal(model.finalMeasurement(value),'1350 × — mm');assert.equal(model.instructionSize(null,'cm'),'—');});

test('order and station components show all cards and recorded values without the blocking warning',()=>{const {Instructions}=load('app/orders/[orderId]/order-detail-client.tsx');for(const item of [poolOrders[0].items[0],{...poolOrders[0].items[0],id:'real-shopify',widthMm:1285,heightMm:2108},{...poolOrders[0].items[0],id:'partial',heightMm:2200}]){const before=structuredClone(item);const html=renderToStaticMarkup(React.createElement(Instructions,{item,index:0}));for(const station of ['MESH','CORD &amp; EYELET','FRAME','ASSEMBLY','QUALITY CONTROL','PACKAGING'])assert.ok(html.includes(station),station);assert.ok(!html.includes('Yetkili kullanıcı'));assert.ok(!html.includes('NaN'));assert.deepEqual(item,before);if(item.id==='real-shopify'){assert.ok(html.includes('1285 × 2108 mm'));assert.ok(!html.includes('Eski prototip'));}const frame=renderToStaticMarkup(React.createElement(Instructions,{item,index:0,onlyStation:'Frame'}));assert.ok(frame.includes('FRAME'));assert.ok(!frame.includes('QUALITY CONTROL'));}});
