import {NextResponse} from 'next/server';
import {cookies} from 'next/headers';
import {getSessionUser,SESSION_COOKIE} from '@/lib/auth';
import {factoryRequests,createFactoryRequest,changeFactoryRequests} from '@/lib/factory-request-server';
import {canViewRequests,canCreateRequests} from '@/lib/factory-requests';
import {productionSnapshot} from '@/lib/production-server';
export const runtime='nodejs';export const dynamic='force-dynamic';
const actor=async()=>getSessionUser((await cookies()).get(SESSION_COOKIE)?.value);
function failure(error:unknown){const message=error instanceof Error?error.message:'';const prefix=message.split(':')[0];const status=prefix==='FORBIDDEN'?403:prefix==='CONFLICT'?409:prefix==='VALIDATION'?400:503;if(status===503)console.error('Factory request failed',error);return NextResponse.json({error:status===503?'Talep hizmetine ulaşılamıyor.':message.slice(prefix.length+1).trim()},{status});}
export async function GET(request:Request){try{const user=await actor();if(!user)return NextResponse.json({error:'Authentication required'},{status:401});if(new URL(request.url).searchParams.has('orders')){if(!canCreateRequests(user))return NextResponse.json({error:'Permission denied'},{status:403});return NextResponse.json({orders:(await productionSnapshot()).orders},{headers:{'Cache-Control':'no-store'}});}return NextResponse.json({requests:await factoryRequests(user),global:canViewRequests(user)},{headers:{'Cache-Control':'no-store'}});}catch(e){return failure(e);}}
export async function POST(request:Request){try{const user=await actor();if(!user)return NextResponse.json({error:'Authentication required'},{status:401});if(request.headers.get('origin')&&request.headers.get('origin')!==new URL(request.url).origin)return NextResponse.json({error:'Invalid origin'},{status:403});if(!request.headers.get('content-type')?.includes('application/json'))return NextResponse.json({error:'JSON required'},{status:415});const raw=await request.text();if(raw.length>6500000)return NextResponse.json({error:'Dosya boyutu çok büyük.'},{status:413});const body=JSON.parse(raw);if(body.action==='create')return NextResponse.json({request:await createFactoryRequest(body.input,user)});if(!Array.isArray(body.changes))return NextResponse.json({error:'Geçersiz seçim'},{status:400});return NextResponse.json({requests:await changeFactoryRequests(body.changes,user)});}catch(e){return failure(e);}}
