"use client";
import { useMemo,useState } from "react";
import { CheckCircle2,ChevronDown,ChevronUp,Search,RefreshCw } from "lucide-react";
import { LegacyShell } from "@/components/legacy-shell";
import { useAuth } from "@/components/auth-provider";
import { useProduction,ProductionNotice } from "@/components/production-provider";
import { config } from "@/components/factory-ui";
import { availableStations,canCompleteStation,workStage,type WorkStation } from "@/lib/production-model";
import { Instructions } from "@/app/orders/[orderId]/order-detail-client";

export default function DailyProduction(){
  const {user}=useAuth();const {snapshot,loading,complete,refresh}=useProduction();
  const [selectedStation,setSelectedStation]=useState<WorkStation|null>(null);const [query,setQuery]=useState("");const [expanded,setExpanded]=useState<string[]>([]);const [busy,setBusy]=useState<string|null>(null);const [error,setError]=useState("");
  const stations=user?availableStations(user):[];const station=selectedStation&&stations.includes(selectedStation)?selectedStation:stations[0];
  const items=useMemo(()=>snapshot.items.filter(item=>station&&item.stage===workStage[station]).sort((a,b)=>a.releasedAt.localeCompare(b.releasedAt)||a.orderId.localeCompare(b.orderId)||a.id.localeCompare(b.id)),[snapshot,station]);
  const visible=items.filter(item=>`${item.orderId} ${item.customer} ${item.name}`.toLowerCase().includes(query.toLowerCase()));
  const orders=[...new Set(visible.map(item=>item.orderId))];
  async function finish(id:string){if(!station||busy)return;setBusy(id);setError("");try{await complete(id,station);}catch(error){setError(error instanceof Error?error.message:"Completion failed.");}finally{setBusy(null);}}
  return <LegacyShell><div className="daily-workspace"><header className="overview-reference-top"><div><span>DAILY PRODUCTION</span><h1>{station??"Daily Production"}</h1><p>Your active work queue. Complete an item to send it to the next station.</p></div><button className="daily-refresh" onClick={()=>void refresh()}><RefreshCw/> Refresh</button></header><ProductionNotice/>{error&&<div className="auth-error" role="alert">{error}</div>}{!loading&&!stations.length?<section className="daily-empty">No station access assigned. Ask an Admin to grant station view and completion permissions.</section>:null}{station&&<><div className="daily-station-tabs" aria-label="Production station">{stations.map(name=><button key={name} className={station===name?"active":""} onClick={()=>{setSelectedStation(name);setError("");}}>{name}<span>{snapshot.items.filter(item=>item.stage===workStage[name]).length}</span></button>)}</div><section className="daily-queue-panel"><header><div><span>ACTIVE WORK QUEUE</span><h2>{station} · {items.length} items</h2><p>{new Set(items.map(item=>item.orderId)).size} orders · {items.reduce((sum,item)=>sum+item.quantity,0)} units · Oldest release first</p></div><label className="daily-search"><Search/><input placeholder="Search order, customer or item…" value={query} onChange={event=>setQuery(event.target.value)}/></label></header>{orders.map(orderId=>{const children=visible.filter(item=>item.orderId===orderId);return <section className="daily-order" key={orderId}><div className="daily-order-heading"><strong>{orderId}</strong><span>{children[0].customer}</span><small>{children.length} items waiting</small></div>{children.map(item=>{const Icon=config[workStage[station]].icon;const open=expanded.includes(item.id);const parent=snapshot.orders.find(order=>order.id===orderId)!;const index=parent.items.findIndex(child=>child.id===item.id);return <div className="daily-item" key={item.id}><div className="daily-item-heading"><button className="daily-item-toggle" aria-expanded={open} onClick={()=>setExpanded(current=>open?current.filter(id=>id!==item.id):[...current,item.id])}><Icon/><span><b>{item.name}</b><small>Item {index+1} · {item.quantity} units · {item.color}</small></span>{open?<ChevronUp/>:<ChevronDown/>}</button><button className="daily-complete" disabled={Boolean(busy)||loading||!user||!canCompleteStation(user,station)} onClick={()=>void finish(item.id)}><CheckCircle2/>{busy===item.id?"Completing…":`Complete ${station}`}</button></div>{open&&<Instructions item={item} index={index} onlyStation={station}/>}</div>})}</section>})}{!loading&&!visible.length&&<div className="daily-empty"><CheckCircle2/><b>{query?"No matching items":"No active work at this station"}</b><span>New work appears here when Admin releases orders or the previous station completes an item.</span></div>}</section></>}</div></LegacyShell>;
}
