"use client";
import {useI18n,LanguageSelector} from "@/components/i18n-provider";
import { FormEvent, useEffect, useState } from "react";
import Image from "next/image";
import { useRouter } from "next/navigation";
import { useAuth } from "@/components/auth-provider";
export default function SetupPage(){ const {t,locale} = useI18n(); 
  const router=useRouter();const {refresh}=useAuth();const [ready,setReady]=useState<boolean|null>(null);const [name,setName]=useState("");const [username,setUsername]=useState("");const [password,setPassword]=useState("");const [token,setToken]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);
  useEffect(()=>{fetch("/api/auth/setup").then(r=>r.json()).then(data=>setReady(Boolean(data.setupRequired))).catch(()=>setReady(false));},[]);
  async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError("");try{const response=await fetch("/api/auth/setup",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,username,password,setupToken:token})});const data=await response.json();if(!response.ok)throw new Error(data.error??"Setup failed");await refresh();router.replace("/");}catch(e){setError(e instanceof Error?e.message:"Setup failed");}finally{setBusy(false);}}
  return <main className="auth-screen"><div className="auth-language-tools"><LanguageSelector/></div><section className="auth-card"><div className="auth-brand"><Image src="/rescro-logo.png" alt="RESCRO" width={180} height={56} priority/></div><span className="auth-kicker">{t("INITIAL SETUP")}</span><h1>{t("Create the first Admin")}</h1><p>{t("This setup is available only while the portal has no users.")}</p>{ready===false?<div className="auth-error">{t("Initial setup is already complete. ")}<a href="/login">{t("Go to login")}</a>.</div>:ready===null?<p>{t("Checking setup status…")}</p>:<form onSubmit={submit}><label>{t("Name")}<input value={name} onChange={e=>setName(e.target.value)} required/></label><label>{t("Username / Email")}<input autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} placeholder={"admin@rescro.com"} required/></label><label>{t("Password")}<input type="password" autoComplete="new-password" minLength={12} value={password} onChange={e=>setPassword(e.target.value)} required/><small>{t("At least 12 characters.")}</small></label><label>{t("One-time setup code")}<input type="password" autoComplete="off" value={token} onChange={e=>setToken(e.target.value)} required/></label>{error?<div className="auth-error" role="alert">{t(error)}</div>:null}<button disabled={busy}>{busy ? t("Creating Admin…") : t("Create Admin")}</button></form>}</section></main>;
}
