'use client';
import {useCallback,useEffect,useState} from 'react';
import Link from 'next/link';
import {useAuth} from '@/components/auth-provider';
import {Button} from '@/components/ui/button';
import {Badge} from '@/components/ui/badge';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {canDoTask,taskStation,jobSpecifications,type FactoryRequest,type TaskStation} from '@/lib/factory-requests';
export function FactoryRequestWork({station,query=''}:{station:TaskStation;query?:string}){
 const {user}=useAuth();const [requests,setRequests]=useState<FactoryRequest[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState('');
 const load=useCallback(async()=>{try{const response=await fetch('/api/factory-requests',{cache:'no-store'});const value=await response.json();if(!response.ok)throw new Error(value.error);setRequests(value.requests);setError('');}catch(e){setError(e instanceof Error?e.message:'İşler yüklenemedi');}},[]);
 useEffect(()=>{void load();const timer=setInterval(()=>{if(document.visibilityState==='visible')void load();},8000);return()=>clearInterval(timer);},[load]);
 const rows=requests.filter(r=>!['Reddedildi','İptal Edildi','Kapatıldı'].includes(r.status)&&`${r.orderId} ${r.number}`.toLowerCase().includes(query.toLowerCase())).flatMap(r=>r.jobs.filter(j=>taskStation(j)===station).map(j=>({r,j})));
 async function complete(r:FactoryRequest,jobId:string){setBusy(jobId);try{const response=await fetch('/api/factory-requests',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({changes:[{id:r.id,version:r.version,action:'complete',payload:{jobId,station}}]})});const value=await response.json();if(!response.ok)throw new Error(value.error);await load();}catch(e){setError(e instanceof Error?e.message:'İşlem başarısız');}finally{setBusy('');}}
 return <section className="orders-card factory-work"><header><h2>Fabrika Talepleri</h2><span>{rows.length} aktif iş · {station}</span><Button variant="outline" onClick={()=>void load()}>Yenile</Button></header>{error&&<p role="alert" className="auth-error">{error}</p>}<div className="table-wrap"><Table><TableHeader><TableRow>{['Talep No','Sipariş / Kalem','İşlem / Adet','Üretim Bilgisi','Not','İşlem'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map(({r,j})=><TableRow key={j.id}><TableCell><Badge variant="secondary">Fabrika Talebi</Badge><br/><Link href={`/factory-requests?request=${r.id}`}>{r.number}</Link></TableCell><TableCell><Link href={`/orders/${encodeURIComponent(r.orderId)}`}>{r.orderId}</Link><br/>{j.itemName}</TableCell><TableCell>{j.operation}<br/><strong>{j.quantity} adet</strong>{r.priority==='Acil'&&<Badge variant="destructive">Acil</Badge>}</TableCell><TableCell>{jobSpecifications(j)}<br/>{j.properties}<br/>{j.destination}</TableCell><TableCell className="factory-work-note">{j.note}<br/>{r.description}</TableCell><TableCell>{user&&canDoTask(user,station)&&<Button disabled={!!busy} onClick={()=>void complete(r,j.id)}>{busy===j.id?'Kaydediliyor…':station==='Transport'?'Gönderildi':station==='Packaging'?'Paketlendi':'Complete'}</Button>}</TableCell></TableRow>)}</TableBody></Table></div>{!rows.length&&<p className="factory-empty">Bu istasyonda bekleyen fabrika talebi yok.</p>}</section>;
}
