import Link from "next/link";
import { Box, CheckCircle2, Frame, Grid3X3, Link2, PackageCheck, PackageOpen, ShieldCheck, Wrench } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { orders, stages, type RiskLevel, type Stage } from "@/lib/orders";
const config:Record<Stage,{color:string;soft:string;icon:typeof Box;short:string;performance:number}>={"Waiting for Mesh":{color:"#2563eb",soft:"#e8efff",icon:Grid3X3,short:"Mesh",performance:245},"Cord & Eyelet":{color:"#7c3aed",soft:"#f0e9ff",icon:Link2,short:"Cord & Eyelet",performance:218},"Waiting for Frame":{color:"#0d6efd",soft:"#e7f0ff",icon:Frame,short:"Frame",performance:224},"Waiting for Assembly":{color:"#0f9f9a",soft:"#e4f8f6",icon:Wrench,short:"Assembly",performance:205},"Quality Control":{color:"#0891b2",soft:"#e2f7fb",icon:ShieldCheck,short:"Quality Control",performance:198},"Waiting for Packing":{color:"#f27c14",soft:"#fff0df",icon:PackageOpen,short:"Waiting Packing",performance:176},"Packed":{color:"#16a34a",soft:"#e4f7ea",icon:PackageCheck,short:"Packed",performance:188},"Finished":{color:"#8b32d9",soft:"#f2e8ff",icon:CheckCircle2,short:"Finished",performance:164}};
export function StageBadge({stage}:{stage:Stage}){const item=config[stage];const Icon=item.icon;return <Badge className="stage-badge" style={{color:item.color,background:item.soft}}><Icon/>{stage}</Badge>}
export function RiskBadge({risk}:{risk:RiskLevel}){return <Badge className={`risk-badge ${risk.toLowerCase()}`}><i/>{risk}</Badge>}
export function Flow({linkBase="/"}:{linkBase?:string}){const counts=Object.fromEntries(stages.map(stage=>[stage,orders.filter(order=>order.stage===stage).reduce((sum,order)=>sum+order.quantity,0)]));return <div className="live-flow factory-flow">{stages.map((stage,index)=>{const item=config[stage];const Icon=item.icon;return <Link className="live-station" href={`${linkBase}?stage=${encodeURIComponent(stage)}`} key={stage}><div className="station-top"><span style={{color:item.color,background:item.soft}}><Icon/></span>{stage==="Waiting for Packing"?<Badge className="bottleneck">Bottleneck</Badge>:null}</div><strong>{counts[stage]}</strong><b>{item.short}</b><small>{stage}</small>{index<stages.length-1?<i className="station-arrow">→</i>:null}</Link>})}</div>}
export {config};
