import {workStations,type WorkStation} from '@/lib/production-model';
import type {PoolItem,PoolOrder} from '@/lib/order-pool';
import type {SessionUser} from '@/lib/auth';
export const requestCategories=['Fabrika Bildiri / Yeniden Üretim','Parça Gönderme','Pratik & Gezer / Eksik Bilgi'] as const;
export type RequestCategory=typeof requestCategories[number];
export const requestStatuses=['Onay Bekliyor','Üretime Hazır','Üretime Verildi','Üretimde','Üretim Tamamlandı','Paketlendi','Gönderildi','Reddedildi','İptal Edildi','Bilgi Bekleniyor','Kapatıldı'] as const;
export type RequestStatus=typeof requestStatuses[number];
export const partTypes=['Tül','Perde','Eşik profili','Kanalsız profil','Diğer profil','İp','Köşe kapağı','Bant','Diğer'] as const;
export const remakeReasons=['Yanlış üretim','Hasar','Kargo kaybı','Depoda bulunamadı','Diğer'] as const;
export const infoTopics=['Pratik','Gezer','Ölçü Yok','Geçersiz RAL','Diğer'] as const;
export type TaskStation=WorkStation|'Transport';
export type RequestJob={id:string;itemId:string;itemName:string;original:PoolItem;quantity:number;operation:string;reason:string;widthMm:string;heightMm:string;lengthCm:string;color:string;productType:string;profileType:string;properties:string;note:string;destination:'Müşteriye'|'Depoya';topic:string;expected:string;contactNote:string;lastContact:string;reminders:number;stations:TaskStation[];step:number;releasedAt:string|null;completions:{station:TaskStation;userId:string;userName:string;at:string}[]};
export type RequestAttachment={id:string;name:string;mime:string;data:string};
export type FactoryRequest={id:string;number:string;orderId:string;category:RequestCategory;priority:'Normal'|'Acil';description:string;status:RequestStatus;creatorId:string;creatorName:string;createdAt:string;updatedAt:string;version:number;jobs:RequestJob[];attachments:RequestAttachment[];history:{action:string;userName:string;at:string;detail:string}[]};
export function canViewRequests(user:SessionUser){return user.role==='Admin'||user.role==='Customer Service';}
export function canCreateRequests(user:SessionUser){return user.role==='Admin'||user.role==='Customer Service'||user.permissions.includes('Create Factory Requests');}
export function canEditRequest(user:SessionUser,request:FactoryRequest){return user.role==='Admin'||(request.creatorId===user.id&&['Onay Bekliyor','Bilgi Bekleniyor'].includes(request.status)&&canCreateRequests(user));}
export function canDoTask(user:SessionUser,station:TaskStation){return user.role==='Admin'||(station==='Transport'?user.role==='Transport'&&user.permissions.includes('Manage Shipping'):user.permissions.includes(`Complete ${station}`));}
export function taskStation(job:RequestJob):TaskStation|null{return job.releasedAt&&job.step<job.stations.length?job.stations[job.step]:null;}
export function jobStatus(job:RequestJob):RequestStatus{if(!job.releasedAt)return 'Üretime Hazır';if(job.step===job.stations.length)return 'Gönderildi';const station=taskStation(job);if(station==='Transport')return 'Paketlendi';if(station==='Packaging')return 'Üretim Tamamlandı';return job.step===0?'Üretime Verildi':'Üretimde';}
export function requestProgress(request:FactoryRequest){const total=request.jobs.reduce((n,j)=>n+j.stations.length,0);const done=request.jobs.reduce((n,j)=>n+j.step,0);return {total,done,percent:total?Math.round(done/total*100):0};}
export function recalculateStatus(request:FactoryRequest):RequestStatus{if(['Bilgi Bekleniyor','Kapatıldı','Reddedildi','İptal Edildi','Onay Bekliyor'].includes(request.status))return request.status;if(!request.jobs.some(j=>j.releasedAt))return 'Üretime Hazır';const values=request.jobs.map(jobStatus);const order=['Üretime Hazır','Üretime Verildi','Üretimde','Üretim Tamamlandı','Paketlendi','Gönderildi'] as const;return order.find(s=>values.includes(s))??'Üretime Hazır';}
export function defaultStations(category:RequestCategory,operation:string):TaskStation[]{if(category===requestCategories[2])return [];if(category===requestCategories[0])return [...workStations,'Transport'];if(operation==='Tül'||operation==='Perde')return ['Mesh','Cord & Eyelet','Quality Control','Packaging','Transport'];if(operation==='İp')return ['Cord & Eyelet','Quality Control','Packaging','Transport'];if(operation.includes('profil'))return ['Frame','Quality Control','Packaging','Transport'];return ['Quality Control','Packaging','Transport'];}
export function newJob(item:PoolItem,category:RequestCategory):RequestJob{return {id:crypto.randomUUID(),itemId:item.id,itemName:item.name,original:item,quantity:item.quantity,operation:category===requestCategories[0]?'Yeniden Üretim':category===requestCategories[1]?'Tül':'Eksik Bilgi',reason:remakeReasons[0],widthMm:String(item.widthMm??''),heightMm:String(item.heightMm??''),lengthCm:'',color:item.color,productType:item.name,profileType:'',properties:item.properties??'',note:'',destination:'Müşteriye',topic:infoTopics[0],expected:'',contactNote:'',lastContact:'',reminders:0,stations:defaultStations(category,category===requestCategories[1]?'Tül':''),step:0,releasedAt:null,completions:[]};}
export function validateRequestInput(value:unknown,orders:PoolOrder[]):{orderId:string;category:RequestCategory;priority:'Normal'|'Acil';description:string;jobs:RequestJob[];attachments:RequestAttachment[]}{
 const v=value as Record<string,unknown>;if(!v||!requestCategories.includes(v.category as RequestCategory)||!['Normal','Acil'].includes(String(v.priority)))throw new Error('VALIDATION: Talep türü ve öncelik seçin.');
 const order=orders.find(o=>o.id===v.orderId);if(!order)throw new Error('VALIDATION: Sipariş bulunamadı.');
 const text=(x:unknown,max=5000)=>{if(typeof x!=='string'||x.length>max)throw new Error('VALIDATION: Geçersiz veya çok uzun metin.');return x;};
 if(!Array.isArray(v.jobs)||!v.jobs.length||v.jobs.length>100)throw new Error('VALIDATION: En az bir iş ekleyin.');
 const category=v.category as RequestCategory;const ids=new Set<string>();
 const jobs=v.jobs.map((raw:Record<string,unknown>)=>{const item=order.items.find(i=>i.id===raw.itemId);if(!item||!item.manufactured)throw new Error('VALIDATION: Geçersiz sipariş kalemi.');const id=text(raw.id,100);if(!id||ids.has(id))throw new Error('VALIDATION: İş kimliği tekrarlanıyor.');ids.add(id);
 const quantity=Number(raw.quantity);if(!Number.isInteger(quantity)||quantity<1||quantity>10000)throw new Error('VALIDATION: Adet 1-10000 olmalı.');
 const operation=text(raw.operation,100);if(category===requestCategories[1]&&!partTypes.includes(operation as typeof partTypes[number]))throw new Error('VALIDATION: Parça türü seçin.');
 const reason=text(raw.reason,100);const topic=text(raw.topic,100);if(category===requestCategories[0]&&!remakeReasons.includes(reason as typeof remakeReasons[number]))throw new Error('VALIDATION: Neden seçin.');if(category===requestCategories[2]&&!infoTopics.includes(topic as typeof infoTopics[number]))throw new Error('VALIDATION: Konu seçin.');
 const dimension=(x:unknown)=>{const s=text(x,30);if(s!==''&&(!Number.isFinite(Number(s))||Number(s)<=0||Number(s)>100000))throw new Error('VALIDATION: Ölçü pozitif sayı olmalı.');return s;};
 const widthMm=dimension(raw.widthMm),heightMm=dimension(raw.heightMm),lengthCm=dimension(raw.lengthCm);
 if(category===requestCategories[0]&&(!widthMm||!heightMm))throw new Error('VALIDATION: Üretim ölçüleri eksik.');if(category===requestCategories[1]&&['Tül','Perde'].includes(operation)&&(!widthMm||!heightMm))throw new Error('VALIDATION: Tül / perde ölçüleri eksik.');if(category===requestCategories[1]&&operation.includes('profil')&&!lengthCm)throw new Error('VALIDATION: Profil boyu girin.');
 const stations=defaultStations(category,operation);if(Array.isArray(raw.stations)&&category===requestCategories[1]){const chosen=raw.stations as TaskStation[];if(new Set(chosen).size!==chosen.length||!chosen.length||chosen.some(s=>![...workStations,'Transport'].includes(s)))throw new Error('VALIDATION: İstasyonlar geçersiz.');const ordered=[...workStations,'Transport'].filter(s=>chosen.includes(s as TaskStation)) as TaskStation[];stations.splice(0,stations.length,...ordered);if(!stations.includes('Packaging')||!stations.includes('Transport'))throw new Error('VALIDATION: Paketleme ve gönderim istasyonu gerekli.');}
 const reminders=Number(raw.reminders);if(!Number.isInteger(reminders)||reminders<0||reminders>10000)throw new Error('VALIDATION: Hatırlatma sayısı geçersiz.');
 if(!['Müşteriye','Depoya'].includes(String(raw.destination)))throw new Error('VALIDATION: Gönderim yeri seçin.');
 return {id,itemId:item.id,itemName:item.name,original:{...item},quantity,operation,reason,widthMm,heightMm,lengthCm,color:text(raw.color,100),productType:text(raw.productType,200),profileType:text(raw.profileType,200),properties:text(raw.properties),note:text(raw.note),destination:raw.destination as RequestJob['destination'],topic,expected:text(raw.expected),contactNote:text(raw.contactNote),lastContact:text(raw.lastContact,30),reminders,stations,step:0,releasedAt:null,completions:[]};});
 const attachments=Array.isArray(v.attachments)?v.attachments as RequestAttachment[]:[];if(attachments.length>3)throw new Error('VALIDATION: En fazla 3 dosya.');let bytes=0;for(const f of attachments){text(f.id,100);text(f.name,200);text(f.mime,100);if(!/^[A-Za-z0-9+/]*={0,2}$/.test(f.data)||f.data.length>2800000)throw new Error('VALIDATION: Dosya en fazla 2 MB olmalı.');bytes+=f.data.length;}if(bytes>3500000)throw new Error('VALIDATION: Dosyaların toplam boyutu çok büyük.');
 return {orderId:order.id,category,priority:v.priority as 'Normal'|'Acil',description:text(v.description),jobs,attachments};
}
