import {neon} from '@neondatabase/serverless';
import {randomUUID} from 'node:crypto';
import {ensureAuthSchema,type SessionUser} from '@/lib/auth';
import {productionSnapshot} from '@/lib/production-server';
import {canViewRequests,canCreateRequests,canEditRequest,canDoTask,taskStation,recalculateStatus,legacyInfoCategory,isFabricPart,requestCategories,defaultStations,validateRequestInput,type FactoryRequest,type RequestJob} from '@/lib/factory-requests';
const db=()=>{const url=process.env.DATABASE_URL??process.env.POSTGRES_URL;if(!url)throw new Error('Database unavailable');return neon(url);};
let schema:Promise<void>|undefined;
export function ensureRequestSchema(){return schema??=initialize().catch(e=>{schema=undefined;throw e;});}
async function initialize(){await ensureAuthSchema();await db()`CREATE SEQUENCE IF NOT EXISTS portal_factory_request_no`;await db()`CREATE TABLE IF NOT EXISTS portal_factory_requests(id TEXT PRIMARY KEY,number TEXT UNIQUE NOT NULL,data JSONB NOT NULL,version INTEGER NOT NULL DEFAULT 1,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;}
export async function factoryRequests(user:SessionUser):Promise<FactoryRequest[]>{await ensureRequestSchema();const rows=await db()`SELECT data FROM portal_factory_requests ORDER BY created_at DESC`;const requests=rows.map(row=>row.data as FactoryRequest);if(canViewRequests(user))return requests;return requests.flatMap(r=>{if(['İptal Edildi','Reddedildi','Kapatıldı'].includes(r.status))return [];const jobs=r.jobs.filter(j=>taskStation(j)&&canDoTask(user,taskStation(j)!));return jobs.length?[{...r,jobs,description:r.description,attachments:[],history:[]}]:[];});}
export function evolveRequest(current:FactoryRequest,action:string,payload:Record<string,unknown>,user:SessionUser):FactoryRequest{
 const r=structuredClone(current);const admin=user.role==='Admin';const now=new Date().toISOString();
 const requireAdmin=()=>{if(!admin)throw new Error('FORBIDDEN: Bu işlem yalnızca Admin tarafından yapılabilir.');};
 if(action==='approve'){requireAdmin();if(r.status!=='Onay Bekliyor')throw new Error('CONFLICT: Talep onay beklemiyor.');r.status='Üretime Hazır';}
 else if(action==='reject'||action==='cancel'){requireAdmin();if(['Gönderildi','Kapatıldı','Reddedildi','İptal Edildi'].includes(r.status))throw new Error('CONFLICT: Talep kapalı.');r.status=action==='reject'?'Reddedildi':'İptal Edildi';}
 else if(action==='close'){requireAdmin();if(r.status!=='Bilgi Bekleniyor'&&r.status!=='Gönderildi')throw new Error('CONFLICT: Açık üretim işleri kapatılamaz.');r.status='Kapatıldı';}
 else if(action==='release'){requireAdmin();if(!['Üretime Hazır','Üretime Verildi','Üretimde','Üretim Tamamlandı','Paketlendi'].includes(r.status)||r.category===legacyInfoCategory)throw new Error('CONFLICT: Talep üretime hazır değil.');const ids=payload.jobIds as string[];if(!Array.isArray(ids)||!ids.length||new Set(ids).size!==ids.length||ids.some(id=>!r.jobs.some(j=>j.id===id&&!j.releasedAt&&j.stations.length)))throw new Error('CONFLICT: İş zaten üretime verilmiş veya geçersiz.');if(r.jobs.some(j=>ids.includes(j.id)&&(r.category===requestCategories[0]||isFabricPart(j.operation))&&(!j.widthMm||!j.heightMm)))throw new Error('VALIDATION: Kaynak siparişin üretim ölçüleri eksik. Önce sipariş detayından gerçek ölçüleri girip talebi güncelleyin.');r.jobs=r.jobs.map(j=>ids.includes(j.id)?{...j,releasedAt:now}:j);r.status=recalculateStatus(r);}
 else if(action==='complete'){if(['Reddedildi','İptal Edildi','Kapatıldı'].includes(r.status))throw new Error('CONFLICT: Talep kapalı.');const j=r.jobs.find(j=>j.id===payload.jobId);const station=j&&taskStation(j);if(!j||!station||station!==payload.station)throw new Error('CONFLICT: İş zaten tamamlandı veya başka istasyona geçti.');if(!canDoTask(user,station))throw new Error('FORBIDDEN: İstasyon yetkiniz yok.');j.completions.push({station,userId:user.id,userName:user.name,at:now});j.step++;r.status=recalculateStatus(r);}
 else throw new Error('VALIDATION: Geçersiz işlem.');
 r.version++;r.updatedAt=now;r.history.push({action,userName:user.name,at:now,detail:String(payload.note??'').slice(0,5000)});return r;
}
export async function createFactoryRequest(input:unknown,user:SessionUser){if(!canCreateRequests(user))throw new Error('FORBIDDEN: Talep oluşturma yetkiniz yok.');await ensureRequestSchema();const snapshot=await productionSnapshot();const value=validateRequestInput(input,snapshot.orders);const [seq]=await db()`SELECT nextval('portal_factory_request_no') AS number`;const now=new Date().toISOString();const request:FactoryRequest={...value,id:randomUUID(),number:`FT-${String(seq.number).padStart(6,'0')}`,status:value.category===legacyInfoCategory?'Bilgi Bekleniyor':'Onay Bekliyor',creatorId:user.id,creatorName:user.name,createdAt:now,updatedAt:now,version:1,history:[{action:'created',userName:user.name,at:now,detail:''}]};const sql=db();await sql.transaction([sql`INSERT INTO portal_factory_requests(id,number,data) VALUES(${request.id},${request.number},${JSON.stringify(request)}::jsonb)`,sql`INSERT INTO portal_audit_logs(id,actor_user_id,actor_name,action,entity_type,entity_id,details) VALUES(${randomUUID()},${user.id},${user.name},'factory_request_created','factory_request',${request.id},${JSON.stringify({number:request.number,orderNumber:request.orderId})}::jsonb)`]);return request;}
export async function changeFactoryRequests(changes:{id:string;version:number;action:string;payload:Record<string,unknown>}[],user:SessionUser){await ensureRequestSchema();if(!changes.length||changes.length>200||new Set(changes.map(c=>c.id)).size!==changes.length)throw new Error('VALIDATION: Geçersiz seçim.');const sql=db();const ids=changes.map(c=>c.id);const rows=await sql`SELECT data FROM portal_factory_requests WHERE id IN(SELECT jsonb_array_elements_text(${JSON.stringify(ids)}::jsonb))`;const updates:FactoryRequest[]=[];
 for(const change of changes){const current=rows.find(row=>(row.data as FactoryRequest).id===change.id)?.data as FactoryRequest|undefined;if(!current||current.version!==change.version)throw new Error('CONFLICT: Kayıt değişti. Listeyi yenileyin.');let updated:FactoryRequest;if(change.action==='edit'){if(!canEditRequest(user,current))throw new Error('FORBIDDEN: Yalnızca onaylanmamış kendi talebinizi düzenleyebilirsiniz.');if(current.jobs.some(j=>j.releasedAt)&&user.role!=='Admin')throw new Error('CONFLICT: Üretime verilen işin özellikleri kilitli.');const value=validateRequestInput(change.payload,(await productionSnapshot()).orders);if(value.orderId!==current.orderId)throw new Error('VALIDATION: Talebin kaynak siparişi değiştirilemez.');if(current.jobs.some(j=>j.releasedAt)){if(value.category!==current.category||value.jobs.length!==current.jobs.length||value.jobs.some(j=>!current.jobs.some(old=>old.id===j.id&&old.itemId===j.itemId)))throw new Error('CONFLICT: Aktif talebin işlerini veya türünü değiştiremezsiniz; yeni talep açın.');value.jobs=value.jobs.map(j=>{const old=current.jobs.find(old=>old.id===j.id)!;return {...j,original:old.original,stations:old.stations,step:old.step,releasedAt:old.releasedAt,completions:old.completions};});}updated={...current,...value,status:value.category===legacyInfoCategory?'Bilgi Bekleniyor':current.status==='Bilgi Bekleniyor'?'Onay Bekliyor':current.status,version:current.version+1,updatedAt:new Date().toISOString(),history:[...current.history,{action:'edited',userName:user.name,at:new Date().toISOString(),detail:''}]};}else updated=evolveRequest(current,change.action,change.payload,user);updates.push(updated);}
 // A transaction with an all-or-nothing optimistic version gate prevents duplicate releases and concurrent completions.
 const operation=randomUUID();const result=await sql`WITH input AS MATERIALIZED (SELECT value AS value FROM jsonb_array_elements(${JSON.stringify(updates)}::jsonb)), locked AS MATERIALIZED (
 SELECT r.id,r.version FROM portal_factory_requests r WHERE r.id IN(SELECT value->>'id' FROM input) ORDER BY r.id FOR UPDATE
 ), valid AS (SELECT COUNT(*) AS count FROM locked l JOIN input i ON l.id=i.value->>'id' WHERE l.version=(i.value->>'version')::int-1), changed AS (
 UPDATE portal_factory_requests r SET data=i.value,version=(i.value->>'version')::int,updated_at=NOW() FROM input i WHERE r.id=i.value->>'id' AND r.version=(i.value->>'version')::int-1 AND (SELECT count FROM valid)=${updates.length} RETURNING r.id,r.data
 ), audit AS (
 INSERT INTO portal_audit_logs(id,actor_user_id,actor_name,action,entity_type,entity_id,details) SELECT ${operation}||':'||id,${user.id},${user.name},'factory_request_updated','factory_request',id,jsonb_build_object('number',data->>'number','orderNumber',data->>'orderId','status',data->>'status','version',data->>'version') FROM changed RETURNING id
 ) SELECT COUNT(*)::int AS count FROM changed`;
 if(Number(result[0].count)!==updates.length)throw new Error('CONFLICT: Kayıt başka bir kullanıcı tarafından değiştirildi. Yenileyin.');return updates;
}
