"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowLeft, ClipboardCheck, Grid3X3, Hammer, Link2, PackageOpen, Ruler, ShieldCheck, Undo2 } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import type { PoolItem, PoolOrder } from "@/lib/order-pool";
import { readReleasedIds, returnEntireOrderToPool } from "@/lib/release";

const stations = [["Mesh", Grid3X3], ["Cord & Eyelet", Link2], ["Frame", Ruler], ["Assembly", Hammer], ["Quality Control", ShieldCheck], ["Packaging", PackageOpen]] as const;
type Station = (typeof stations)[number][0];
const stationColor: Record<Station, string> = { Mesh: "#c00000", "Cord & Eyelet": "#ed7d31", Frame: "#c99a00", Assembly: "#70ad47", "Quality Control": "#5b9bd5", Packaging: "#7030a0" };

type Instruction = { curtain:boolean; windowLike:boolean; pollen:boolean; width:number; height:number; piles:number; meshLength:string; cordLength:number; profileColor:string; thresholdColor:string; direction:string; closingDirection:string; montage:boolean; };

function instructionFor(item:PoolItem,index:number):Instruction { const curtain=item.name.includes("Curtain"); const height=2100+index*50; return { curtain, windowLike:item.name.includes("Window")||curtain, pollen:item.name.includes("Pollen")||index%3===1, width:900+index*100, height, piles:45+index*4, meshLength:(height/10-4.2).toFixed(1), cordLength:Math.round((900+index*100+height)/10+20), profileColor:item.color, thresholdColor:index%2?"Black":item.color, direction:index%2?"Vertical":"Horizontal", closingDirection:index%2?"Right":"Left", montage:index%4===0 }; }

function Field({label,value,emphasis=false}:{label:string;value:string;emphasis?:boolean}) { return <div className="detail-field"><dt style={{fontWeight:700,letterSpacing:".02em"}}>{label}</dt><dd style={emphasis?{fontSize:18,fontWeight:850,letterSpacing:".01em"}:undefined}>{value}</dd></div>; }
function StationCard({title,children}:{title:string;children:React.ReactNode}) { return <section className="production-section"><header><h3>{title}</h3><Badge>Production instruction</Badge></header>{children}</section>; }

function FrameRows({instruction}:{instruction:Instruction}) { const rows=[["Kanalsız Profil",`${instruction.meshLength} cm`,`2 ADET`,instruction.profileColor],["Kanallı Profil",`${instruction.meshLength} cm`,`2 ADET`,instruction.profileColor],["Kanat Profil",`${(instruction.height/10).toFixed(1)} cm`,`1 ADET`,instruction.profileColor],["Eşik Profil",`${instruction.meshLength} cm`,`1 ADET`,instruction.thresholdColor]]; const grid={display:"grid",gridTemplateColumns:"1.45fr 1fr .8fr 1fr",gap:12,alignItems:"center",padding:"11px 14px"} as const; return <div style={{border:"1px solid #e6ebf1",borderRadius:9,overflow:"hidden"}}><div style={{...grid,background:"#f7f9fb",borderBottom:"1px solid #e6ebf1",color:"#64748b",fontSize:11,fontWeight:800,textTransform:"uppercase"}}><span>Profil</span><span>Boy</span><span>Adet</span><span>Renk</span></div>{rows.map(([profile,length,quantity,color],rowIndex)=><div style={{...grid,borderBottom:rowIndex<rows.length-1?"1px solid #edf1f5":undefined,color:"#334155",fontSize:14}} key={profile}><strong style={{color:"#172033",fontSize:14}}>{profile}</strong><span>{length}</span><Badge variant="secondary" style={{justifySelf:"start",fontSize:10,fontWeight:800}}>{quantity}</Badge><span>{color}</span></div>)}</div>; }

function Instructions({item,index}:{item:PoolItem;index:number}) { const data=instructionFor(item,index); const meshType=data.pollen?"POLLEN":"STANDARD"; return <div style={{display:"grid",gap:12,marginTop:14}}>
  <StationCard title="MESH"><div className="detail-grid three"><Field label="TÜL TÜRÜ" value={meshType} emphasis/><Field label="PILE SAYISI" value={String(data.piles)}/><Field label="TÜL BOYU" value={`${data.meshLength} cm`}/><Field label="İP BOYU" value={`${data.cordLength} cm`}/>{data.curtain&&<><Field label="PERDE TÜRÜ" value="Perdeli Sineklik"/><Field label="PERDE RENGİ" value={item.color}/></>}</div></StationCard>
  <StationCard title="CORD & EYELET"><div className="detail-grid three"><Field label="İP BOYU" value={`${data.cordLength} CM`} emphasis/><Field label="TÜL TÜRÜ" value={meshType}/><Field label="PILE SAYISI" value={String(data.piles)}/><Field label="TÜL BOYU" value={`${data.meshLength} cm`}/></div></StationCard>
  <StationCard title="FRAME"><div className="frame-section-heading"><Field label="PROFİL RENGİ" value={data.profileColor} emphasis/></div><FrameRows instruction={data}/></StationCard>
  <StationCard title="ASSEMBLY"><div className="detail-grid three"><Field label="ÜRÜN RENGİ" value={item.color}/><Field label="KAPANMA YÖNÜ" value={data.closingDirection}/><Field label="KAPANMA TÜRÜ" value="Magnetic"/><Field label="TAKOZ / KAPAK RENGİ" value={data.profileColor}/><Field label="EŞİK TÜRÜ" value="Standard"/><Field label="TÜL TÜRÜ" value={meshType}/>{data.windowLike&&<Field label="ÜRÜN YÖNÜ" value={data.direction}/>}</div></StationCard>
  <StationCard title="QUALITY CONTROL"><div className="detail-grid three"><Field label="FINAL ÖLÇÜ" value={`${data.width} × ${data.height} mm`} emphasis/><Field label="RENK" value={item.color}/><Field label="TÜL TÜRÜ" value={meshType}/><Field label="KAPANMA TÜRÜ" value="Magnetic"/><Field label="KAPANMA YÖNÜ" value={data.closingDirection}/>{data.windowLike&&<Field label="ÜRÜN YÖNÜ" value={data.direction}/>}</div></StationCard>
  <StationCard title="PACKAGING"><div className="detail-grid three"><Field label="ÖLÇÜ" value={`${data.width} × ${data.height} mm`} emphasis/><Field label="RENK" value={item.color}/><Field label="MONTAJ" value={data.montage?"EVET – MONTAJ HİZMETİ VAR":"HAYIR – MÜŞTERİ KENDİ MONTAJ EDECEK"} emphasis/></div></StationCard>
</div>; }

function Flow({inProduction}:{inProduction:boolean}) { return <div className="item-flow" aria-label="Production flow">{stations.map(([name,Icon],index)=><div className="item-flow-step" key={name}><div className="item-flow-line"><span style={{color:stationColor[name]}}><Icon/></span>{index<stations.length-1?<i/>:null}</div><strong>{name}</strong><Badge variant="secondary">{inProduction&&index===0?"In Progress":"Pending"}</Badge></div>)}</div>; }

export default function OrderDetailClient({order}:{order:PoolOrder}) { const [released,setReleased]=useState<Set<string>>(()=>new Set()); useEffect(()=>{const sync=()=>setReleased(readReleasedIds());sync();window.addEventListener("rescro-release-updated",sync);return()=>window.removeEventListener("rescro-release-updated",sync);},[]); const productionItems=order.items.filter(item=>released.has(item.id)); const [firstName,lastName=""]=order.customer.split(" "); const totalQuantity=order.items.reduce((sum,item)=>sum+item.quantity,0); const returnOrder=()=>{returnEntireOrderToPool(order.id);setReleased(readReleasedIds());}; return <main className="order-detail-page"><header className="detail-topbar"><Link href="/" className="detail-logo">RESCRO</Link><div className="detail-actions"><Link href="/" className="back-link"><ArrowLeft/> Orders</Link></div></header><div className="detail-container"><Link href="/" className="return-link"><ArrowLeft/> Back to Orders</Link><section className="order-summary"><Field label="Sipariş Numarası" value={order.id}/><Field label="Adı" value={firstName}/><Field label="Soyadı" value={lastName}/><Field label="Toplam Kalem" value={String(order.items.length)}/><Field label="Toplam Adet" value={String(totalQuantity)}/><Field label="Sipariş Tarihi" value={order.date}/></section>{productionItems.length>0&&<div className="item-card-toolbar"><span>Return this complete order to Order Pool.</span><button type="button" onClick={returnOrder}><Undo2/> Return Entire Order to Order Pool</button></div>}<div className="items-heading"><div><h1>Order Items</h1><p>All production instructions are visible for admin review.</p></div><Badge>{order.items.length} ITEMS</Badge></div>{order.items.map((item,index)=>{const inProduction=released.has(item.id);return <article className="order-item-card" key={item.id}><header className="item-card-header"><div><span className="item-number">{index+1}</span><div><h2>Order Item {index+1} · {item.name}</h2><p>Quantity: {item.quantity} · Color: {item.color}</p></div></div><Badge className={inProduction?"current-stage":""}>{inProduction?"In Production":"Not Selected"}</Badge></header><Flow inProduction={inProduction}/><Instructions item={item} index={index}/></article>;})}<section className="package-section"><header><div><h2>Order production summary</h2><p>Original Shopify order stays intact; selected production items are tracked below it.</p></div><ClipboardCheck/></header><strong>{productionItems.length} of {order.items.length} items released to production</strong></section></div></main>; }
