"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { ArrowDown, ArrowUp, Clock3, PackageSearch, Search, Timer } from "lucide-react";
import { LegacyShell } from "@/components/legacy-shell";
import { StageBadge } from "@/components/factory-ui";
import { orders, stages, type Stage } from "@/lib/orders";

type SortKey = "stationWait" | "production" | "date";
type DelayFilter = "all" | "7-13" | "14-20" | "21+";
const delayLabel=(days:number)=>days>=14?"Long Delay":"Delayed";

export default function DelayedRisk(){
  const [search,setSearch]=useState(""); const [station,setStation]=useState<"all"|Stage>("all"); const [delay,setDelay]=useState<DelayFilter>("all"); const [sort,setSort]=useState<SortKey>("stationWait"); const [direction,setDirection]=useState<"asc"|"desc">("desc");
  const delayed=useMemo(()=>orders.filter(order=>order.stage!=="Finished"&&order.ageDays>7).map(order=>({...order,stationWaitDays:order.stageEnteredDays})),[]);
  const filtered=useMemo(()=>delayed.filter(order=>{const term=search.trim().toLowerCase();const matchesSearch=!term||order.id.toLowerCase().includes(term)||order.customer.toLowerCase().includes(term);const matchesStation=station==="all"||order.stage===station;const matchesDelay=delay==="all"||delay==="7-13"&&order.ageDays<=13||delay==="14-20"&&order.ageDays>=14&&order.ageDays<=20||delay==="21+"&&order.ageDays>=21;return matchesSearch&&matchesStation&&matchesDelay;}).sort((a,b)=>{const aValue=sort==="stationWait"?a.stationWaitDays:a.ageDays;const bValue=sort==="stationWait"?b.stationWaitDays:b.ageDays;return direction==="desc"?bValue-aValue:aValue-bValue;}),[delayed,search,station,delay,sort,direction]);
  const longestProduction=Math.max(...delayed.map(order=>order.ageDays),0); const longestStationWait=Math.max(...delayed.map(order=>order.stationWaitDays),0);
  function chooseSort(key:SortKey){if(sort===key)setDirection(current=>current==="desc"?"asc":"desc");else{setSort(key);setDirection("desc");}}
  function SortHeading({label,sortKey}:{label:string;sortKey:SortKey}){const active=sort===sortKey;return <button className={`delay-sort ${active?"active":""}`} onClick={()=>chooseSort(sortKey)}>{label}{active?(direction==="desc"?<ArrowDown/>:<ArrowUp/>):null}</button>;}
  return <LegacyShell><div className="delayed-reference-view"><header className="delayed-reference-top"><div><span>DELAYED / RISK ORDERS</span><h1>Delayed Orders</h1><p>Orders that have been in production for more than 7 days.</p><small>Identify where delayed orders are currently waiting and how long they have been in that stage.</small></div></header><section className="delayed-kpis"><article><i><PackageSearch/></i><div><b>Delayed orders</b><strong>{delayed.length}</strong><small>Orders over 7 days</small></div><em/></article><article><i><Clock3/></i><div><b>Longest delay</b><strong>{longestProduction} days</strong><small>Longest active production time</small></div><em/></article><article><i><Timer/></i><div><b>Longest station wait</b><strong>{longestStationWait} days</strong><small>Longest wait in current station</small></div><em/></article></section><section className="delayed-orders-panel"><header className="delayed-panel-heading"><div><span>DELAYED ORDERS</span><h2>Orders waiting in production</h2><p>Sorted by longest wait in the current station.</p></div><b>{filtered.length} orders</b></header><div className="delayed-filters"><label className="delay-search"><Search/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search order number or customer…"/></label><label><span>Station</span><select value={station} onChange={event=>setStation(event.target.value as "all"|Stage)}><option value="all">All Stations</option>{stages.filter(item=>item!=="Finished").map(item=><option key={item} value={item}>{item}</option>)}</select></label><label><span>Delay</span><select value={delay} onChange={event=>setDelay(event.target.value as DelayFilter)}><option value="all">All Delayed</option><option value="7-13">7–13 Days</option><option value="14-20">14–20 Days</option><option value="21+">21+ Days</option></select></label></div><div className="delayed-table-wrap"><div className="delayed-table-head"><span>Order Number</span><SortHeading label="Order Date" sortKey="date"/><span>Current Station</span><SortHeading label="Days in Production" sortKey="production"/><SortHeading label="Days in Current Station" sortKey="stationWait"/><span>Status / Delay</span></div>{filtered.map(order=><div className="delayed-table-row" key={order.id}><Link href={`/orders/${encodeURIComponent(order.id)}`} target="_blank">{order.id}<small>{order.customer}</small></Link><span>{order.date}</span><StageBadge stage={order.stage}/><strong>{order.ageDays} days</strong><strong className="station-wait">{order.stationWaitDays} days</strong><b className={order.ageDays>=14?"long-delay":"delayed"}>{delayLabel(order.ageDays)}</b></div>)}{!filtered.length?<div className="delayed-empty">No delayed orders match the selected filters.</div>:null}</div></section></div></LegacyShell>;
}
